SPLIT_KEYBOARD = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes 
COMMAND_ENABLE = no
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
SEND_STRING_ENABLE = yes

# RGBLIGHT_ENABLE = yes
# RGBLIGHT_DRIVER = ws2812
# WS2812_DRIVER_REQUIRED = yes
# WS2812_DRIVER = bitbang
